### PR TITLE
Added a new Section and fourteen (14) new Article 

### PR DESCRIPTION
**Pull request by Kiri23**
1. I added a new section called Newsletter that contain 4 articles 
2. I added two new article to the course section 
3. I added one new article to the video section 
4. I added five new article to the resource section 
5. I added one new article to the book section 
6. I adde four new article to the Articles & Post section

### CODE REVIEW

**Comment by Kiri23** [comment]
I will add in the next days articles for Big O notation.

**Comment by cmanny** [comment]
Thanks @Kiri23 ! Will wait for those articles?

**Comment by Kiri23** [comment]
Done.  😉   👍 . @cmanny

**Comment by Kiri23** [comment]
Thanks.

**Pull request merged**
